# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aaronsnotebooks',
                'doc_host': 'https://aaronsgithub.github.io',
                'git_url': 'https://github.com/aaronsgithub/aaronsnotebooks',
                'lib_path': 'aaronsnotebooks'},
  'syms': {'aaronsnotebooks.core': {'aaronsnotebooks.core.foo': ('core.html#foo', 'aaronsnotebooks/core.py')}}}
